### ISSUE TITLE
Troubles with the pakage

### ISSUE THREAD

**Issue by budarin** [developit/preact-render-to-string#19]
Hi!
Thanks for the package!
I have some problems withe the package - help me please.

I try to use to preact-render-to-string on server side to render component:

App.jsx
----------------------------------------
```
import { h } from 'preact';
const App = () => {
    return <h1>App</h1>;
};
export default App;
```

serverEntry.js
---------------------------------------------------------
```
import { h } from 'preact';
import render from 'preact-render-to-string';
import App from '../common/components/App.jsx';
const serverEntry = () => {
    return render(<App />);
};
export default serverEntry;
```

Server.js
------------------------------------------------------
```
import serverEntry from '../../serverEntry.js';
....
html = html.replace('<div id="app"></div>', serverEntry());
```
In my project I use to babel-env preset with target = 'node'.
When I add preact-render-to-string package to the project and try to transpile it with webpack - it breaks with error: 'Module build failed: Error: Couldn't find preset "es2015-minimal" relative to directory "D:\\Projects\\app1\\node_modules\\preact-render-to-string"'

It strange little bit....

so I add es2015-minimal to the project and again try to transpile, but now I get another warning:

```
node_modules\nan
resolve failed:  { Error: Cannot find module 'caniuse-db'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (D:\Projects\app1\node_modules\require-relative\index.js:30:17)
    at resolve (D:\Projects\app1\node_modules\modify-babel-preset\lib\serialize.js:26:26)
    at findAndRemove (D:\Projects\app1\node_modules\modify-babel-preset\lib\serialize.js:83:11)
    at D:\Projects\app1\node_modules\modify-babel-preset\lib\serialize.js:126:13
    at Array.map (native)
    at loadPreset (D:\Projects\app1\node_modules\modify-babel-preset\lib\serialize.js:118:29)
    at module.exports (D:\Projects\app1\node_modules\modify-babel-preset\index.js:95:19)
    at Object.<anonymous> (D:\Projects\app1\node_modules\babel-preset-es2015-minimal\index.js:5:18)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Projects\app1\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:270:20)
    at OptionManager.mergePresets (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:259:10)
    at OptionManager.mergeOptions (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:244:14)
    at OptionManager.init (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (D:\Projects\app1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\Projects\app1\node_modules\babel-loader\lib\index.js:38:20)
    at Object.module.exports (D:\Projects\app1\node_modules\babel-loader\lib\index.js:133:12)
    at LOADER_EXECUTION (D:\Projects\app1\node_modules\loader-runner\lib\LoaderRunner.js:114:14)
    at runSyncOrAsync (D:\Projects\app1\node_modules\loader-runner\lib\LoaderRunner.js:115:4) code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (D:\Projects\app1\node_modules\require-relative\index.js:30:17)
    at resolve (D:\Projects\app1\node_modules\modify-babel-preset\lib\serialize.js:26:26)
    at findAndRemove (D:\Projects\app1\node_modules\modify-babel-preset\lib\serialize.js:83:11)
    at D:\Projects\app1\node_modules\modify-babel-preset\lib\serialize.js:126:13
    at Array.map (native)
    at loadPreset (D:\Projects\app1\node_modules\modify-babel-preset\lib\serialize.js:118:29)
    at module.exports (D:\Projects\app1\node_modules\modify-babel-preset\index.js:95:19)
    at Object.<anonymous> (D:\Projects\app1\node_modules\babel-preset-es2015-minimal\index.js:5:18)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Projects\app1\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:270:20)
    at OptionManager.mergePresets (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:259:10)
    at OptionManager.mergeOptions (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:244:14)
    at OptionManager.init (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (D:\Projects\app1\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (D:\Projects\app1\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\Projects\app1\node_modules\babel-loader\lib\index.js:38:20)
    at Object.module.exports (D:\Projects\app1\node_modules\babel-loader\lib\index.js:133:12)
    at LOADER_EXECUTION (D:\Projects\app1\node_modules\loader-runner\lib\LoaderRunner.js:114:14)
    at runSyncOrAsync (D:\Projects\app1\node_modules\loader-runner\lib\LoaderRunner.js:115:4) code: 'MODULE_NOT_FOUND' } babel-runtime
```
What is wrong?
Thanks

P.S. you can reproduce it https://github.com/budarin/app

**Comment by budarin** [comment]
I'm sorry - here was an error in my webpack config

**Comment by developit** [comment]
No problem!
