### ISSUE TITLE
Fails when using hooks

### ISSUE THREAD

**Issue by johannesodland** [developit/preact-render-to-string#72]
The current hooks implementation rely on vnodes having a _component property. The property is created during rendering and is passed to the hooks implementation by options.render (used to be options.beforeRender).

Preact-render-to-string does not store the _component property, nor does it offer a way to pass it to the hooks implementation. 

As a result preact-render-to-string fails when rendering components with hooks:

```
TypeError: Cannot read property '__H' of undefined
    at f (.../node_modules/preact/hooks/dist/hooks.js:1:369)
    at c (.../node_modules/preact/hooks/dist/hooks.js:1:465)
    at exports.useState (.../node_modules/preact/hooks/dist/hooks.js:1:1235)
    at HooksComponent (...)
    at s (.../node_modules/preact-render-to-string/dist/index.js:1:1470)
```

**Comment by vaneenige** [comment]
@johannesodland the issue was reported on https://github.com/developit/preact/issues/1373 and is being looked at. 🙌
